### ISSUE TITLE
Build Error after adding

### ISSUE THREAD

**Issue by Skquark** [NilsBacke/PHSpeechBubble#1]
I was looking forward to using the speech bubbles, but when I added it to my yaml and built my project, I get this error:
```
* What went wrong:
A problem occurred configuring project ':speech_bubble'.
> Could not find method debugProvided() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```
I'm using latest Flutter & Dart dev versions, have done a flutter clean, and also have multiDex enabled, in case that matters.  I did not investigate the error deeply, but thought I should bring it up.. Thanks.

**Comment by NilsBacke** [comment]
Fixed! The project was missing a critical file in the android/ folder. Be sure to update to the latest version (0.0.4). Thank you!
