### ISSUE TITLE
Change type of padding parameter

### ISSUE THREAD

**Issue by yura2000** [NilsBacke/PHSpeechBubble#9]
Please, change type of padding parameter to EdgeInsets, because I can not change padding for SpeechBubble widget
![Screenshot_1](https://user-images.githubusercontent.com/11773084/65136851-f4a07880-da10-11e9-8862-4d9f7b21aa66.png)

**Comment by NilsBacke** [comment]
This is because I have not published the latest version of this repo. I will do that later today and let you know.

**Comment by NilsBacke** [comment]
Should be all set 👍
